# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Dockerfile for DART MCP server
FROM python:3.10-slim

# Install dependencies
WORKDIR /app
COPY pyproject.toml ./
COPY uv.lock ./
# If there was requirements, but use pip to install project and dependencies
RUN pip install --no-cache-dir .

# Copy the rest of the server code
COPY . /app

# Default command (will be overridden by MCP startCommand)
CMD ["python", "dart.py"]
