# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

# Use official Python runtime
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install dependencies
# Copy pyproject.toml and any lock files
COPY pyproject.toml .
# Copy any lock or requirement files
COPY uv.lock .

# Install pip dependencies
RUN pip install --no-cache-dir pip setuptools wheel && \
    pip install --no-cache-dir .

# Copy application source
COPY . .

# Expose no ports (stdio-based)

# Default command
CMD ["python", "dart.py"]
